CREATE TABLE IF NOT EXISTS `embassies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(128) DEFAULT NULL,
  `slug` varchar(128) DEFAULT NULL,
  `heading` varchar(128) DEFAULT NULL,
  `excerpt` text DEFAULT NULL,
  `image_url` varchar(512) DEFAULT NULL,
  `logo` text DEFAULT NULL,
  `right_heading_image` text DEFAULT NULL,
  `additional_images` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`additional_images`)),
  `google_map` text DEFAULT NULL,
  `your_location` text DEFAULT NULL,
  `content` text DEFAULT NULL,
  `working_time` text DEFAULT NULL,
  `address` varchar(512) DEFAULT NULL,
  `phone` varchar(512) DEFAULT NULL,
  `emergency_phone` text DEFAULT NULL,
  `email` varchar(40) DEFAULT NULL,
  `website_link` text DEFAULT NULL,
  `fax` text DEFAULT NULL,
  `country_id` int(11) DEFAULT NULL,
  `city_id` int(11) DEFAULT NULL,
  `sort_order` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `fk_embassies_country` (`country_id`),
  CONSTRAINT `fk_embassies_country` FOREIGN KEY (`country_id`) REFERENCES `countries` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=778 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
